title: Justin A. Gould
description: AI & Data Engineering Leader
show_downloads: true
theme: jekyll-theme-cayman
github:
  cv_url: https://raw.githubusercontent.com/gouldju1/gouldju1/master/CV/Gould_Resume.pdf
  repository_url: https://github.com/gouldju1/gouldju1
  home_url: https://gouldju1.github.io/gouldju1/
  papers_url: https://gouldju1.github.io/gouldju1/thoughtleadership
  projects_url: https://gouldju1.github.io/gouldju1/projects